apiVersion: gpte.redhat.com/v1
kind: AgnosticVRepo
metadata:
  name: test-agnosticv-repo
spec:
  url: "https://git.example.com/myrepo"
  ref: master
  sshKey: agnosticv-key
  babylonAnarchyGovernorRepo: https://github.com/redhat-gpte-devopsautomation/babylon_anarchy_governor.git
  babylonAnarchyGovernorVersion: master

