apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- argocd
- babylon
- dispatcher
resources:
- lodestar-tools.yaml 
- lodestar-engagements.yaml
patches:
- patch: |-
    - op: add
      path: /spec/project
      value: lodestar-tools
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
- patch: |-
    - op: add
      path: /metadata/namespace
      value: lodestar-argo-cd
  target:
    group: argoproj.io
    version: v1alpha1
